% Clear workspace but preserve paths and settings
clearvars -except code_dir root_dir data_path output_path fig_path tab_path log_path int_path ...
    updatedata bootstrap runbootstrap ncores nbs;
clc;
bondtypes=(readtable(fullfile(data_path,'bondtypes.csv'),'ReadVariableNames',true));
aucidbonds_short=table2array(bondtypes(:,2));
bondidlocs_short=table2array(bondtypes(:,10));
aucidbonds=[]; bonddlocs=table(repmat(bondidlocs_short,6,1));
count=1;
%get all permutations of each bond id...keep it with an auction then
%extract to a text file.
for kk=1:size(bondidlocs_short,1)
    bt={bondidlocs_short{kk}; bondidlocs_short{kk}(1:end-1);bondidlocs_short{kk}(2:end);bondidlocs_short{kk}(3:end);bondidlocs_short{kk}(3:end-1);bondidlocs_short{kk}(2:end-1)};
    bonddlocs(count:count+size(bt,1)-1,:)=array2table(bt);
    count=count+size(bt,1);
    aucidbonds=[aucidbonds; aucidbonds_short(kk).*ones(size(bt,1),1)];
end
writetable(bonddlocs,fullfile(int_path,'bondpermutations.txt'));
%this is what you query for bonds in wharton wrds trace database

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: gosyop23q6grk5y1.csv (in data_path)
%
% Auto-generated by MATLAB on 17-Nov-2024 14:18:18

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["cusip_id1", "bond_sym_id1", "company_symbol1", "date", "tradetime", "quantity", "quantity_ind", "price"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "datetime", "datetime", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["cusip_id1", "bond_sym_id1", "company_symbol1", "quantity_ind"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "tradetime", "InputFormat", "HH:mm:ss");

% Import the data
tbl = readtable(fullfile(data_path,'gosyop23q6grk5y1.csv'), opts);

%% Convert to output type
cusip_id = tbl.cusip_id1;
bond_sym_id = tbl.bond_sym_id1;
company_symbol = tbl.company_symbol1;
date = tbl.date;
tradetime = tbl.tradetime;
quantity = tbl.quantity;
quantity_ind = tbl.quantity_ind;
price = tbl.price;

%% Clear temporary variables
clear opts tbl

[bondslist,ic]=unique(cusip_id);
comp_list=unique(company_symbol(ic));
bonddlocs=table2array(bonddlocs);
for ii=1:size(bondslist,1)
    for jk=1:length(bonddlocs)
        if isequal(bonddlocs{jk},bondslist(ii))
            aucidbond_list(ii)=aucidbonds(jk);
        end
    end
end

for ii=1:size(price,1)
    if isequal(quantity_ind(ii),'E')
    quantity(ii)=1000000;
    end
end
save(fullfile(int_path,'bondprices'))
date=datetime(date);
matchedauc=unique(aucidbond_list);
%loop over bonds 
auctionlistid=(readtable(fullfile(data_path,'auctionlistid.csv'),'ReadVariableNames',true));
for ii=1:size(matchedauc,2)
%keep relavent dates 30 before and after.--for each one pull the prices and
%quanties
%find bonds in that auction in the right date range
%compare within/across bond cusips: try to get a reference for CTD vs
%auction price risk.
auciddate=table2array(auctionlistid(:,[5:8]));
fu=find(auciddate(:,4)==matchedauc(ii));
auciddate=auciddate(fu,:);
auctiondate=datetime(auciddate(1:3))
bonds_int=bondslist(aucidbond_list==matchedauc(ii));

%drop bonds quoted in other units where prices don't make sense
bonds_int(bonds_int=="812404408")=[];
bonds_int(bonds_int=="812404507")=[];


ptemp=NaN.*ones(size(bonds_int,1),1);
qtemp=NaN.*ones(size(bonds_int,1),1);
pstd=NaN.*ones(size(bonds_int,1),1);
for jk=1:61
current=auctiondate+days(jk-31);
for pp=1:size(bonds_int,1)
ptemp(pp)=sum(price(date==current & cusip_id==bonds_int(pp)).*quantity(date==current & cusip_id==bonds_int(pp)))./sum(quantity(date==current & cusip_id==bonds_int(pp)));
qtemp(pp)=sum(quantity(date==current & cusip_id==bonds_int(pp)));
pstd(pp)=std(price(date==current & cusip_id==bonds_int(pp)));
end
%eliminate weird price quotes--within day at least
ptemp(ptemp>nanmedian(ptemp)+20)=NaN;
BPsd(ii,jk)=mean(pstd);
BPmean(ii,jk)=nanmean(ptemp);
BP_sdmeanxbond(ii,jk)=nanstd(ptemp);
BP_spread(ii,jk)=max(ptemp)-min(ptemp);
BPvol(ii,jk)=nansum(qtemp);
end
end
save(fullfile(int_path,'bondprices'))
